apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongodb-secret-{{ .Values.environment }}
data:
  mongo-root-username: {{ .Values.secret.username }}
  mongo-root-password: {{ .Values.secret.password }}