apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-{{ .Values.environment }}
spec:
  selector:
    app: mongodb-{{ .Values.environment }}
  ports:
  - protocol: TCP
    port: {{ .Values.mongoImage.servicePort }}
    targetPort: {{ .Values.mongoImage.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service-{{ .Values.environment }}
spec:
  selector:
    app: mongo-express-{{ .Values.environment }}
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.expressImage.servicePort }}
    targetPort: {{ .Values.expressImage.containerPort }}
    nodePort: {{ .Values.expressImage.nodePort }}