# Default values for mongo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

servicePort: 8083

nodePort: 30000

configmap: 
  name: mongodb-configmap-dev

secret: 
  name: mongodb-secret-dev

mongoDB:
  databaseUrl: mongodb-service
  mongorootusername: dXNlcm5hbWU=
  mongorootpassword: cGFzc3dvcmQ=