apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  mongo-root-username: {{ .Values.mongoDB.mongorootusername }}
  mongo-root-password: {{ .Values.mongoDB.mongorootpassword }}