apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-mono
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amadinathaniel/deploying-to-kubernetes.git
    targetRevision: HEAD
    path: mongo-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true